# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20171011_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_facebookuser_friends_+', to='model.FacebookUser'),
        ),
    ]
